# Generated by Django 6.0.4 on 2026-04-29 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('grains', 'Grains & Cereals'), ('pulses', 'Pulses & Legumes'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('dairy', 'Dairy Products'), ('meat', 'Meat & Poultry'), ('fish', 'Fish & Seafood'), ('nuts', 'Nuts & Seeds'), ('oils', 'Oils & Fats'), ('beverages', 'Beverages'), ('sweets', 'Sweets & Snacks'), ('eggs', 'Eggs'), ('spices', 'Spices & Condiments'), ('other', 'Other')], default='other', max_length=20)),
                ('calories_per_100g', models.FloatField(help_text='Calories per 100 grams')),
                ('serving_unit', models.CharField(default='g', help_text='e.g., g, ml, piece', max_length=50)),
                ('default_serving_g', models.FloatField(default=100, help_text='Default serving size in grams')),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('unit', models.CharField(help_text='e.g., mg, mcg, g, IU', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_100g', models.FloatField(help_text='Amount of this nutrient per 100g of the food')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='foods.fooditem')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_nutrients', to='foods.nutrient')),
            ],
            options={
                'ordering': ['food_item', 'nutrient'],
                'unique_together': {('food_item', 'nutrient')},
            },
        ),
    ]
